### ISSUE TITLE
An experience report

### ISSUE THREAD

**Issue by michaellenaghan** [thanethomson/statik#102]
I like Statik very much. I can explain why if that's of interest, but the purpose of this particular issue is to offer an experience report; that's more likely to be of value.

To be very clear: none of this is meant as criticism. As I said, I like Statik very much.

1.

I'd love to be able to specify more about models. In particular, I'd love to be able to express the cardinality of each field in a model—especially so that I can say which fields are optional and which are required.

2.

View routes are functions of one parameter, but I immediately ran into a case where I wanted two: I wanted to organize blog-ish posts by category (with /\<category slug>/\<post slug> paths).

Note that there are two separate implications here, one related to the way that routes are expressed (I'd like to iterate over categories, and for each category over that category's posts) and one related to reverse route template tags, which only accept one optional param.

3.

It's very difficult to show previous/next links on blog posts. As a workaround I tried using pagination, with a count of 1, but I ran into two issues. The first is that it was ugly; in the templates I had to refer to each post as "page.items[0]". Second, I couldn't generate paths, because the thing passed into the route path is a paginator rather than a post. (The "items[0]" trick didn't work there.)

I thought about creating my own pagination-like function, but that function is privileged; the query compiler specifically loads it into its compilation environment. That's something I can't do myself.

I also thought about creating my own previous/next template tags, but previous/next depend on the query used to generate the sequence of pages, and I don't have access to the exact same query that's generating the sequence I'm actually using; I'd have to use two copies of the same query in two different places and keep them in sync.

4.

Speaking of which: I found myself creating the same query in multiple places anyway. For example, the list of posts on the home page and the list of posts defined in the post view need the same query. I can't define the query once at the project level because I can't reference a "global" sequence from a view's path generator.

5.

On a somewhat related note: I don't seem to have centralized access to all possible routes, something that would be useful, for example, when generating a sitemap file. (This is "somewhat related" because the workaround is to have project-level or sitemap-specific view-level queries that replicate the queries used in any views of interest.)

6.

It's difficult to elegantly define navigation. Here are three examples. First, I can define my main menu using static context, but in doing that I have to hard-code route paths since there's no way to reverse a route in that context. Second, it's not easy to write generic code that figures out which page is active in a menu; templates have access to mostly SQLAlchemy instances and have to work to generically figure out what the instance represents. Third, it's not easy to implement breadcrumbs generically, since breadcrumbs are often tree paths but Statik's routes aren't trees.

7.

Assets are assumed to be in a subdirectory of the output (the asset destination can't be the root of the output), but there are some things like favicons (e.g., robots.txt) that really want to be in the root. (For textual files like robots.txt I *could* create views and templates, but that's really just a workaround.)

===

All of those are fairly low-level points related to specific goals. Here are two higher-level comments that are more firmly in the realm of opinion.

A.

One thing I really like about Statik is the way it breaks out its key ideas. Having benefited from that effort, I can see that I'd use somewhat different terminology.

 * What Statik calls "Model" I'd call the "Meta-Model".
 * What Statik calls "Data" I'd call "Model".
 * What Statik calls "View" I'd call "ViewModel".
 * What Static calls "Template" I'd call "View".

The terminology comes from [this](https://en.wikipedia.org/wiki/Model–view–viewmodel). The terminology is useful, but I think it's the conceptual model that's *really* useful; I think it provides some answers to some of the issues above. For example, the tree of routes is a ViewModel thing; each node in the tree represents a "page"; pages are passed into Views; pages have their own identity (their paths), which makes figuring out the active page easier; pages have parents and children, which makes generating navigation and breadcrumbs easier; etc.

B.

I think I understand the thinking behind the use of SQLAlchemy, but having used Statik I'm now not convinced it's worth the cost.

First, if you aren't a SQLAlchemy user, there's a ramp-up cost. (I've been a Django user rather than a SQLAlchemy user.) For example, I had to figure out how to filter posts by specific categories (where categories are a related model), and I had to figure out how to lookup individual categories correctly. Those weren't a big deal, but I'm not sure there was any payoff either; I haven't really needed the power of SQLAlchemy in what I've been doing.

Second, by using SQLAlchemy Statik subjects itself to leaky abstractions—which include, I think, SQLAlchemy's errors and error messages.

You definitely need a model of some kind, but something simpler might suffice; pretty much everything I've had to do could have been easily done using list comprehensions, for example. 

===

Thanks for such an interesting tool!

**Comment by thanethomson** [comment]
Thanks for the detailed feedback! :+1:

Good to hear about your experience with Statik. What I'd recommend, however, is to break down each of your requests/pain points above into separate issues here on GitHub (just copy/paste them into separate issues). This way it's easier to look at addressing each feature/issue separately. If you've got suggestions on how to implement each feature or fix an issue, please describe that in that issue, or even better, fix it yourself and submit a pull request :grin:

As such, I'm closing this for now.
