### ISSUE TITLE
Any Statik community around to ask questions related to flask..?

### ISSUE THREAD

**Issue by dennohpeter** [thanethomson/statik#121]
The title is pretty clear if any...drop the link here...opening an issue everytime you want support or clarification sucks...
@thanethomson @jayvdb

**Comment by dennohpeter** [comment]
Telegram, gitter, whatsapp, RFC or any other

**Comment by softwarebandit** [comment]
I would suggest using stackoverflow. A lot of projects use it as a support forum. And you get more eyes to look at the issue you’re having.

**Comment by dennohpeter** [comment]
Ok
