### ISSUE TITLE
"C:\Python34\Scripts\statik" is not an executable file, how to run “> statik"？

### ISSUE THREAD

**Issue by gofficer** [thanethomson/statik#17]
"C:\Python34\Scripts\statik" is not an executable file, how to run “> statik"？

**Comment by gofficer** [comment]
I try to change filename "statik" into "statik.py" ,then run "statik",output :
Traceback (most recent call last):
  File "C:\Python34\Scripts\statik.py", line 3, in <module>
    from statik import main
  File "C:\Python34\Scripts\statik.py", line 3, in <module>
    from statik import main
ImportError: cannot import name 'main'

**Comment by thanethomson** [comment]
I've just pushed a new version now (v0.2.5) that should (hopefully) take care of this. It's because Windows isn't explicitly catered for yet, but I'm now attempting to use `setuptools`' [standard automatic script creation](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) functionality to try to cater for Windows too.

I unfortunately don't have access to a Windows machine (I'm on OSX and Ubuntu) - @gofficer could you please test on your machine and see if it works?

Upgrade command should be something like (to get the new version):

```bash
C:\somewhere> pip install --upgrade statik
```

Please let me know if this works, and I'll close this issue if it does :grinning:

**Comment by gofficer** [comment]
Thank you for your reply.

Upgrade and run "statik", output:
Traceback (most recent call last):
  File "C:\Python34\Scripts\statik-script.py", line 9, in <module>
    load_entry_point('statik==0.2.5', 'console_scripts', 'statik')()
  File "C:\Python34\lib\site-packages\setuptools-23.0.0-py3.4.egg\pkg_resources\
__init__.py", line 542, in load_entry_point
  File "C:\Python34\lib\site-packages\setuptools-23.0.0-py3.4.egg\pkg_resources\
__init__.py", line 2569, in load_entry_point
  File "C:\Python34\lib\site-packages\setuptools-23.0.0-py3.4.egg\pkg_resources\
__init__.py", line 2229, in load
  File "C:\Python34\lib\site-packages\setuptools-23.0.0-py3.4.egg\pkg_resources\
__init__.py", line 2235, in resolve
  File "C:\Python34\lib\site-packages\statik\__init__.py", line 2, in <module>
    from statik.generator import generate
  File "C:\Python34\lib\site-packages\statik\generator.py", line 3, in <module>
    from statik.project import StatikProject
  File "C:\Python34\lib\site-packages\statik\project.py", line 13, in <module>
    from statik.database import StatikDatabase
  File "C:\Python34\lib\site-packages\statik\database.py", line 318
    **kwargs,
            ^
SyntaxError: invalid syntax

**Comment by thanethomson** [comment]
This is very strange. I've managed to find a computer running Windows to test my installation, and installing v0.2.5 with the latest version of Python (3.5.1) for Windows it works perfectly, no issues.

Could you please supply some more detailed information about your system? (Version of Windows? Exact command line? What exactly are you compiling with Statik? etc.)

You could also try Python 3.5.1 (I'm not sure if 3.5 introduced some incompatibilities with 3.4.x, but I've built Statik to work with Python 3.5.1 at the moment).

**Comment by gofficer** [comment]
Installed Python (3.5.1), still running failed.What`s wrong with me ?
System: cn_windows_7_ultimate_with_sp1_x64
Python: python-3.5.1-amd64.exe

Command:
C:\>pip install statik
Collecting statik
  Using cached statik-0.2.5.tar.gz
Collecting jinja2==2.8 (from statik)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting PyYAML==3.11 (from statik)
  Using cached PyYAML-3.11.zip
Collecting SQLAlchemy==1.0.13 (from statik)
  Using cached SQLAlchemy-1.0.13.tar.gz
Collecting markdown==2.6.6 (from statik)
  Downloading Markdown-2.6.6.zip (412kB)
    34% |███████████▏                    | 143kB 2.6MB/s eta 0:00:01
    ....
    100% |████████████████████████████████| 413k
B 656kB/s
Collecting MarkupSafe (from jinja2==2.8->statik)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: MarkupSafe, jinja2, PyYAML, SQLAlchemy, markdown,
 statik
  Running setup.py install for MarkupSafe
  Running setup.py install for PyYAML
  Running setup.py install for SQLAlchemy
  Running setup.py install for markdown
  Running setup.py install for statik
Successfully installed MarkupSafe-0.23 PyYAML-3.11 SQLAlchemy-1.0.13 jinja2-2.8
markdown-2.6.6 statik-0.2.5
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
C:\>python -m pip install --upgrade pip
Collecting pip
  Using cached pip-8.1.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.2
E:\statik-master\examples\blog>pip install --upgrade statik
Requirement already up-to-date: statik in c:\program files\python35\lib\site-pac
kages
Requirement already up-to-date: jinja2==2.8 in c:\program files\python35\lib\sit
e-packages (from statik)
Requirement already up-to-date: PyYAML==3.11 in c:\program files\python35\lib\si
te-packages (from statik)
Requirement already up-to-date: SQLAlchemy==1.0.13 in c:\program files\python35\
lib\site-packages (from statik)
Requirement already up-to-date: markdown==2.6.6 in c:\program files\python35\lib
\site-packages (from statik)
Requirement already up-to-date: MarkupSafe in c:\program files\python35\lib\site
-packages (from jinja2==2.8->statik)
E:\statik-master\examples\blog>statik
failed to create process.

**Comment by thanethomson** [comment]
That's very strange indeed. Have you perhaps tried installing Statik into a virtual environment?

See [`virtualenv` installation](https://virtualenv.pypa.io/en/stable/installation/) and [`virtualenv` usage](https://virtualenv.pypa.io/en/stable/userguide/).

**Comment by gofficer** [comment]
Maybe I should go back to Linux and use it...

**Comment by thanethomson** [comment]
Don't give up just yet :grinning: It's weird that it worked on the version of Windows that I was using. Perhaps there's some kind of conflict somewhere, or perhaps you need to uninstall the version you have installed and install cleanly.

Installing in a virtual environment will be a quick and easy way of installing with a "clean slate".

**Comment by gofficer** [comment]
All right. Let me use the virtual machine to install win7, and then try it again.
What is the version of your Windows ?

**Comment by thanethomson** [comment]
I tried it on Windows 10.

**Comment by gofficer** [comment]
OK, I also use windows10.

**Comment by thanethomson** [comment]
@gofficer: Did you manage to get it working?

**Comment by gofficer** [comment]
Yes, it working on Windows 10. Sorry, I`m late. A busy day.
Thank you for your help.

**Comment by thanethomson** [comment]
Awesome, thanks for letting me know!
