### ISSUE TITLE
Certain characters not handled properly

### ISSUE THREAD

**Issue by pztrick** [thanethomson/statik#22]
Left- and right- angled quotes are not handled properly in the Markdown-HTML:

Original:

```
“AS IS”
```

Output:

```
 â€œAS ISâ€
```

**Comment by pztrick** [comment]
The source `.md` file is encoded `UTF-8` so it is probably just being coerced to `ASCII` or something somewhere.

**Comment by thanethomson** [comment]
Fixed handling these non-standard characters in `v0.5.1`. New unit test added: https://github.com/thanethomson/statik/blob/master/tests/modular/test_nonascii.py (just tests the two characters you're talking about here - will expand on this if more errors come up).

Used this as solution: http://stackoverflow.com/questions/1061697/whats-the-easiest-way-to-escape-html-in-python

**Comment by toxadx** [comment]
It is not good solution, since "not reserved characters" (e.g. cyrillic) are also escaped.
Markdown and HTML permits usage of non-ascii characters.

Please use another solution.
