### ISSUE TITLE
Unable to render two views (a simple and other complex) to same folder

### ISSUE THREAD

**Issue by viniciusbraga** [thanethomson/statik#26]
For some reason, I am not able to render a "Simple View" (/articles/index.html) to the same folder of one "Complex View" (/articles/{{ post.slug }}/). However, the simple view renders properly when I change the folder name of the complex view.

**Comment by thanethomson** [comment]
Sorry for the delay in getting back to you @viniciusbraga, was out-of-country for a few days. I've pushed a new version to fix this issue: v0.6.6
