### ISSUE TITLE
Can't have multiple foreign keys in the same document

### ISSUE THREAD

**Issue by emacsen** [thanethomson/statik#27]
I created a model, let's just call it Foo in this example, so

Foo.yml contains

Title: String
Value: Integer

and then let's say I want to have Bar contain multiple Foo's

Bar.yml contains

foo1: Foo
foo2: Foo

I can't- I get an error such as:

Error caught: Could not determine join condition between parent/child
tables on relationship Bar.foo1 - there are multiple foreign key
paths linking the tables.  Specify the 'foreign_keys' argument,
providing a list of those columns which should be counted as
containing a foreign key reference to the parent table.
Unable to clean up properly: 'NoneType' object has no attribute 'shutdown'

I'm unsure how to resolve this other than by creating foo1 and foo2 models, but that seems very ugly.

**Comment by thanethomson** [comment]
Yes, you're right - that's one feature for which I haven't catered at the moment. It'll require quite a bit of refactoring to add that as a feature, but I'm going to label this as an enhancement for a future release. (It's a little complicated in SQLAlchemy as it is to have multiple different keys pointing to a single model, and even more so when you're constructing it dynamically :grinning:).

In the meantime, you could look at using a `ManyToMany` relationship perhaps?
