### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by non-Jedi** [thanethomson/statik#33]
Is there any chance we could specify minimum acceptable versions of dependency packages and just manage breaking changes as they come? I don't have access to virtualenv in my current setup, so I haven't been able to install statik yet because of version requirements conflicting with what's already installed on my system.

As an example, this is the approach Pelican currently takes.
https://github.com/getpelican/pelican/blob/master/setup.py

**Comment by thanethomson** [comment]
Done 😁 Try it out now and let me know if it works? New version: `v0.9.1`.

**Comment by non-Jedi** [comment]
Perfect. Thank you!
