### ISSUE TITLE
Exit with non-zero status code upon error

### ISSUE THREAD

**Issue by tylerdave** [thanethomson/statik#35]
I'd like to chain the `statik` command with `&&` and then another command to upload the generated output.

However as it is `statik` exits with a 0 status whether successful or not so I have to perform other checks before I can upload.

I could probably submit a PR for this if it's something you'd want to incorporate.

**Comment by thanethomson** [comment]
Sounds like a cool feature! How would that work though? Would Statik have to output a simple list of file paths, which would be fed into another command?

Try start out with describing the command into which you want to feed Statik's output, and the kind of input it can take from stdin?

**Comment by thanethomson** [comment]
Also, what kind of upload mechanism are we talking here? FTP? SFTP? It may actually be a really cool feature to build directly into Statik itself. Python's got awesome libs that can do that quite easily.

I'm away at the moment unfortunately, but I could actually start adding this feature later this week 😀

**Comment by tylerdave** [comment]
I'm actually only talking about changing the exit code and not any other output (for this issue.)

I'm using http://surge.sh/ to host a simple site so my use case is to run:
``statik && surge public/``

But I'd only want surge to run if statik ran successfully. If there was an error and `statik` still exits with a code of 0, `surge` still runs and uploads a potentially broken version of the site.

If `statik` was changed to exit with `sys.exit(1)` upon any error then the second command would not be run, allowing me to fix the issue before running the upload command.

**Comment by thanethomson** [comment]
Sorry for the delay in getting back to you! I've now released [v0.16.1](https://github.com/thanethomson/statik/releases/tag/v0.16.1) to return proper non-zero exit codes when an exception is thrown during processing.

Please check it out and let me know if it works for your purposes?

**Comment by tylerdave** [comment]
Works perfectly. Thanks!
