### ISSUE TITLE
can u publish the source code of your site: https://thanethomson.com/ to your github a/c?

### ISSUE THREAD

**Issue by luckypoem** [thanethomson/statik#36]
hi.

i like ur site: https://thanethomson.com/ ,u can just not upload ur source posts,just upload a demo source post.

thank u very much!

**Comment by thanethomson** [comment]
Thanks! 😁

I can definitely put it up on GitHub. Will do so a little later this week!

**Comment by luckypoem** [comment]
hi.

today is sunday.are u free to publish the source code of your site: https://thanethomson.com/ to your github a/c?

thank u very much!

**Comment by thanethomson** [comment]
Sorry for the delay! [Here's the newly-created repo](https://github.com/thanethomson/blog).
