### ISSUE TITLE
Consider to merge with Lektor

### ISSUE THREAD

**Issue by somenxavier** [thanethomson/statik#38]
I think you and [Lektor](https://www.getlektor.com/) seek same aims. Consider to merge it and make a better final product.

**Comment by thanethomson** [comment]
I've looked at Lektor previously actually, and while it is really cool, its model is conceptually more complex for me personally than what I've implemented with Statik. If it were as simple a thing as merging features into two different code bases, that could possibly make sense, but merging conceptual models is far harder. (See [Lektor's Data Modelling approach](https://www.getlektor.com/docs/models/) - I personally think that Statik's approach is more flexible for my own use cases, but some people might find Lektor's to be easier or more applicable).

Also, while two different projects may have the same aims, how a project implements those aims is incredibly important, along with developers' subjective preferences, and it's okay for developers to prefer one way of doing things over another.

**Comment by somenxavier** [comment]
I thought your implementation differ (sql and yaml-like fields) each other but the philosophy is the same.

**Comment by thanethomson** [comment]
No, Lektor allows you to define a model _for a specific piece of content_ and one "model instance" (in Statik's terminology) has to be associated with a single template (see Lektor's [Content](https://www.getlektor.com/docs/content/) docs).

Statik, on the other hand, allows you to access multiple model instances (and different kinds of models) from any template by way of dynamic, highly configurable querying. _Views_ are the magic glue that connect templates to model instances in Statik, where I can't find such an analogue in Lektor.
