### ISSUE TITLE
How to disable html entities?

### ISSUE THREAD

**Issue by FuzzyWuzzie** [thanethomson/statik#50]
Given that utf-8 is everywhere nowadays, I would like to just use unicode symbols in my markdown source files (such as `θ`), and leave them as their unicode symbol (ie `θ`, not `&#952;`). This particularly messes with inline code (between \` tags).

If my source file contains:

```markdown
Some text with a `θ` in it
```

It renders to:

```html
<p>Some text with a <code>&#952;</code> in it</p>
```

Which of course displays as:

> Some text with a `&#952;` in it

Instead of what I want, which is:

> Some text with a `θ` in it

Thanks!

**Comment by tombreit** [comment]
Escaping the backticks should be enough: 
````
# data/Model/myfile.md
Some text with a \`θ\` in it
````
Should render as:

Some text with a \`θ\` in it


or, if you do not need those backticks in your rendered output at all, omit them: 

````
# data/Model/myfile.md
Some text with a θ in it
````
should render as: 

Some text with a θ in it

**Comment by FuzzyWuzzie** [comment]
Escaping the backticks isn't what I want though; I want to surround the θ with `<code>` tags using Markdown (instead of relying on inserting html `<code>` tags.

And again, just leaving the θ in the source file translates it into an HTML entity, which I don't want to do—I want to leave it untouched, since we live in a Unicode world nowadays.

**Comment by thanethomson** [comment]
I've attempted to replicate your use case in the unit testing as best I can in Statik v0.21.2 - try it out and let me know if it works for you?

**Comment by FuzzyWuzzie** [comment]
Definitely fixed my issue, thanks! Though now I'm getting something different:

`Template error: isoformat() argument 1 must be char, not unicode (in file "./templates/feed-atom.xml.jinja2").`

I'm looking into this though and will make a new issue if I can't get around it.
