### ISSUE TITLE
Document using raw python in views

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#52]
Hi, 

you mention that raw python could be used in views [1]. But how do I actually set a static context variable via raw python code? 

Especially, how to use a multiline python construct in this yaml view?

My use case is: a python for-loop over all files (images) in a specific directory and making this variable (a list) available to my ``base.html`` template. 

[1] https://github.com/thanethomson/statik/wiki/Querying-data

**Comment by thanethomson** [comment]
For this kind of use case, I'd highly recommend writing a [custom template tag](https://github.com/thanethomson/statik/wiki/Custom-template-tags-and-filters).

**Comment by tombreit** [comment]
Thanks for the hint and your support, exactly what I need.
