### ISSUE TITLE
Hours-minute not accepted in DateTime

### ISSUE THREAD

**Issue by PaulPichaureau** [thanethomson/statik#59]
The DateTime information

    last-modified: 2018-01-14 15:03

is not accepted by statik.

    Error: Failed to build project. Run Statik in verbose mode (-v) to see additional traceback information about this error. Additional error detail: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.

But it should be. See: https://www.sqlite.org/lang_datefunc.html

**Comment by thanethomson** [comment]
This seems to work now that I'm using `python-dateutil` to parse date/time fields that aren't automatically picked up by the YAML parsing process. See v0.21.0.

**Comment by PaulPichaureau** [comment]
Ok, the Date+Hour format works now, but it seems that any DateTime field is now mandatory (and not optional).

**Comment by thanethomson** [comment]
I see - fixed that now in v0.21.1.
