### ISSUE TITLE
Strange behaviour for self-referencing model

### ISSUE THREAD

**Issue by PaulPichaureau** [thanethomson/statik#60]
Given the following model:

    Name: String
    Parent: Category

and the following datas

    papa.md
    ---
    Name: Papa
    ---

    child1
    ---
    Name: Child1
    Parent: papa
    ---

    child2
    ---
    Name: Child2
    Parent: papa
    ---

I can see that `child1` and `child2` object generated by a view as no attribute `Parent`, but `papa` has one, and it is a list of two value `child1` and `child2`.

Is it the expected behaviour?

**Comment by thanethomson** [comment]
I've just enabled basic support for self-referential models in v0.21.0.
