### ISSUE TITLE
`encode` in html entities not required

### ISSUE THREAD

**Issue by PaulPichaureau** [thanethomson/statik#63]
Hi,

in the file `markdown_exts.py` of the version 0.21.1 there are two lines that look like

    result.append(line.encode("ascii", "xmlcharrefreplace").decode("utf-8"))

It seems that the markdown files is supposed in encoded in `utf-8` and then encoded in `ascii` using html entities.

But this feature ignores completely the encoding given by the user. Moreover, the final encoding should be unicode, not ascii!

I think this should be changed either using specified encoding in the configuration file or at least unicode.

**Comment by FuzzyWuzzie** [comment]
I think this is related to #50 and it's super annoying.

**Comment by thanethomson** [comment]
Try Statik v0.21.2 and let me know if that works for you?

**Comment by PaulPichaureau** [comment]
Seems to work as expected! Thanks!
